#!/bin/bash

# Autor: Hézio Silva
# Objetivo: Realizar a cópia dos arquivos inseridos por seus caminhos(origem/destino)  
# de forma automática, criando para cada execução um LOG que exiba os stderr e o stdout
# de cada execução e se por acaso um arquivo que vai ser copiado já exista, o programa
# realiza um backup do mesmo para que não ocorra a subscrição.

DATA=$(date +%H%M%S%d%m%Y)

cd /home/oem/Documentos/arquivosRTC

echo "-=-=-=-=-=-="
echo "Informe o RTC: "
read rtc

echo "____________"
cd $rtc

mkdir -p LOGS

CAMINHO=$(pwd)

ARQLOG="$DATA-$rtc.log"
echo "Iniciando..." >> $ARQLOG 2>&1

echo "-----------------------------" >> $ARQLOG 2>&1

while read p; do
  ORIGEM=`echo "$p" | awk -F';' '{ print $1 }'`
  DESTINO=`echo "$p" | awk -F';' '{ print $2 }'`
  LAST=$(basename $ORIGEM)
  
  if [ -e "$DESTINO"/"$LAST" ]; then
          BACKUP=`cp -r "$DESTINO"/"$LAST" "$DESTINO/$DATA-backup_$LAST"`
  fi
  
  RESULT=`cp -r "$ORIGEM" "$DESTINO" 2>&1`
  
  if [ "$?" -ne 0 ]
  then
    echo "$DATA ERRO em copiar o arquivo $ORIGEM: $RESULT" >> $ARQLOG 2>&1
    else
    echo "$DATA SUCESSO em copiar de: $ORIGEM para $DESTINO" >> $ARQLOG 2>&1
    fi
echo "_____" >> $ARQLOG 2>&1
done < arquivoConf.txt

echo "_______________________________________________" >> $ARQLOG 2>&1
echo "Quantidade de erros: " >> $ARQLOG 2>&1
grep ERRO $ARQLOG |wc -l >> $ARQLOG 2>&1
echo "_______________________________________________" >> $ARQLOG 2>&1

mv $CAMINHO/$ARQLOG $CAMINHO/LOGS

echo "Shell executado!"
echo "Confira os resultados em arqLog.txt"
echo $DATA
